// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser, LocalTokenGroup} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "&YQQOPOOOcOQO'#C_OqOPO'#CiO!VOPO'#CgOOOO'#Cp'#CpQQOPOOOOOO'#Ca'#CaO!hOQO,59TOOOO,58y,58yOOOO,59T,59TO!sOQO'#C_OOOO'#Cq'#CqO!{OPO'#CfOOOO'#Cl'#ClO#aOPO'#CrO#uOPO'#CeO#uOPO'#CeO$WOPO'#CtO$lOPO'#CdO$lOPO'#CdO$zOPO'#C^OOOO,58x,58xOOOO'#Cs'#CsO%VOPO,59ROOOO,59R,59ROOOO-E6n-E6nOOOO,58{,58{OOOO1G.o1G.oO%hOQO'#CaOOOO-E6o-E6oOOOO,59^,59^OOOO-E6p-E6pO%mOPO,59POOOO,59`,59`OOOO-E6r-E6rOOOO,59O,59OO$lOPO,59OOOOO-E6q-E6qOOOO1G.m1G.mOOOO1G.j1G.j",
  stateData: "&R~OSPO[ROaSObSOjSO~OUVOVUO^XO_XO~OSYO[ROa]Ob]Oc]OjZO~OSPO[hOafObfOjfO~OVjO^kO_kO~OUlOVUO~OjZOSYX[YXaYXbYXcYX~OjZOSfX[fXafXbfXcfX~O[ROSXXaXXbXXcXX~O[ROjZOShXahXbhXchX~OSYOa]Ob]Oc]O~OSYO[ROjZO~OSPO[vOafObfOjfO~OVjO~O[ROSXaaXabXacXa~OSa~",
  goto: "$]iPPjyP!WPP![!`!g!oP!{PP#TPPP#_#e#n#z$QSSOTYaQbcdtTfRgWQORTgZdQbcdtTWPYTeQdScQdRqaU`QadRn^SSOT]^Q_`adpSSOTTfRgQXQSsbcRwtQTORiTW[Q^adRm[U_QadSo_pRp`QgRRugSbQdSrbtRtc",
  nodeNames: "⚠ TextColor Expression TcLeft LMarker Description Color InnerMarker TcRight Text Word CodeSection CODE Unfinished ColorEOF ColorWS REnd RMarker ENDLN EOF",
  maxTerm: 26,
  skippedNodes: [0],
  repeatNodeCount: 5,
  tokenData: "%l~RbXY!ZYZ!`]^!Zpq!Zqr!Zrs!Zs#O!Z#O#P!m#P#S!Z#S#T$d#T#q!Z#q#r$i#r#s$|#s;'S!Z;'S;=`%a<%l~!Z~O!Z~~%g~!`Oj~~!ePj~YZ!h~!mOb~~!rYj~rs!Z!P!Q!Z#O#P!Z#S#T!Z#U#V!Z#Y#Z!Z#b#c!Z#f#g!Z#h#i!Z#i#j#b~#eR!Q![#n!c!i#n#T#Z#n~#qR!Q![#z!c!i#z#T#Z#z~#}R!Q![$W!c!i$W#T#Z$W~$ZR!Q![!Z!c!i!Z#T#Z!Z~$iO[~~$nPj~uv$q~$tP#r#s$w~$|Oa~~%RPj~uv%U~%XP#o#p%[~%aOS~~%dP;=`<%l!Z~%lOc~",
  tokenizers: [1, new LocalTokenGroup("!X~R[X^wpqw#q#r|#y#zw$f$gw#BY#BZw$IS$I_w$I|$JOw$JT$JUw$KV$KWw&FU&FVw~~!R~|O_~~!ROV~~!WO^~~", 54, 6)],
  topRules: {"TextColor":[0,1]},
  tokenPrec: 230
})
